<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Cetak extends CI_Controller
{
  function __construct()
  {
      parent::__construct();
      $this->load->model('data_model');
      $this->load->library('pdf');
      date_default_timezone_set("Asia/Jakarta");
    //   if($this->session->userdata('login_form') != "grafamedia_admin"){
    //       redirect(base_url("login"));
    //   }
  }
  function index(){
    echo "";
  }
  
  function pkwt(){
    $token = $this->uri->segment(3);
    $wicode = $this->uri->segment(4);
    $ar = array(
      '00' => 'Undf','01' => 'Januari', '02' => 'Februari', '03' => 'Maret', '04' => 'April', '05' => 'Mei', '06' => 'Juni', '07' => 'Juli', '08' => 'Agustus', '09' => 'September', '10' => 'Oktober', '11' => 'November', '12' => 'Desember'
    );
    $cektoken = $this->data_model->get_byid('pkwt', ['sha1(idpkwt)'=>$token]);
    if($cektoken->num_rows() == 1){
    $nopkwt = $cektoken->row("nosurat");
    $nrp = $cektoken->row("nrp");
    $tanggal_awal = $cektoken->row("tanggal_awal");
    $tanggal_berakhir = $cektoken->row("tanggal_berakhir");
    $upah = $cektoken->row("upah_pokok");
    $_upah50persen = $upah * 0.5;
    $_upahsetengah = round($_upah50persen);
    $tunjab = $cektoken->row("tunjangan_jabatan");
    $premi = $cektoken->row("premi_kehadiran");
    $masa_tahun = $cektoken->row("masa_tahun");
    $masa_bulan = $cektoken->row("masa_bulan");
    $ttd = $cektoken->row("ttd");
    $tgl_ttd = $cektoken->row("tgl_ttd");
    $x = explode('-', $tanggal_awal);
    $y = explode('-', $tanggal_berakhir);
    $tanggal_awal_dt = mktime(0, 0, 0, $x[1], $x[2], $x[0]);
    $tanggal_berakhir_dt = mktime(0, 0, 0, $y[1], $y[2], $y[0]);
    $selisih = $tanggal_berakhir_dt - $tanggal_awal_dt;
    $_tahun = floor($selisih / (365 * 24 * 60 * 60));
    $_bulan = floor(($selisih % (365 * 24 * 60 * 60)) / (30 * 24 * 60 * 60));
    $_hari = floor(($selisih % (30 * 24 * 60 * 60)) / (24 * 60 * 60));
    $wwal = explode('-', $tanggal_awal);
    $wakhir = explode('-', $tanggal_berakhir);
    $_wawal = $wwal[2].' '.$ar[$wwal[1]].' '.$wwal[0];
    $_wakhir = $wakhir[2].' '.$ar[$wakhir[1]].' '.$wakhir[0];
    $kar = $this->data_model->get_byid('data_karyawan' , ['nrp'=>$nrp])->row_array();
    $nama_karyawan = $kar['nama'];
    $departement = $kar['departement'];
    $jabatan = $kar['jabatan'];
    $divisi = $kar['divisi'];
    $nik = $kar['no_ktp'];
    $tmp = $kar['tmp_lahir'];
    $alamat = $kar['alamat'];
    $kel = $kar['kel'];
    $kec = $kar['kec'];
    $kota = $kar['kabkota'];
    $nohp = $kar['nohp'];
    $email = $kar['email'];
    $x = explode('-', $kar['tgl_lahir']);
    $printTgl = $x[2].' '.$ar[$x[1]].' '.$x[0];
    $ttl = $tmp.", ".$printTgl;
    
        $ex = "tes";
        $printTgl = "Tes Tanggal";
        $nosj = "nosj";
       
             $pdf = new FPDF('p','mm','A4');
              // membuat halaman baru
              $pdf->AddPage();
              // setting jenis font yang akan digunakan
              $pdf->SetTitle('PKWT - '.$nama_karyawan.'');
      
              $pdf->SetFont('Arial','B',14);
              $pdf->Image('https://data.rdgjt.com/assets/logo_rjs2.jpg', 13, 8, 35, 0, 'JPG');
              $pdf->Cell(0, 6, 'PT RINDANG JATI SPINNING', 0, 0, 'C' );
              $pdf->SetFont('Arial','',9);
              $pdf->Ln(6);
              $pdf->Cell(0, 6, 'JALAN RAYA JATIREJO, NO. 47, RT.004/RW.001', 0, 0, 'C' );
              $pdf->Ln(5);
              $pdf->Cell(0, 6, 'KEL. JATIREJO - KEC. AMPELGADING', 0, 0, 'C' );
              $pdf->Ln(5);
              $pdf->Cell(0, 6, 'KAB. PEMALANG - JAWA TENGAH', 0, 0, 'C' );
              $pdf->Ln(5);
              $pdf->Cell(0, 6, 'TELP / FAX : (0285) 5750073', 0, 0, 'C' );
              $pdf->Line(13, 38, 210-15, 38);
              $pdf->Line(13, 38.1, 210-15, 38.1);
              $pdf->Line(13, 38.2, 210-15, 38.2);
              $pdf->Line(13, 38.8, 210-15, 38.8);
              $pdf->Ln(8);
              $pdf->Cell(0, 6, 'PERJANJIAN KONTRAK KERJA WAKTU TERTENTU (PKWT)', 0, 0, 'C' );
              $pdf->Line(60, 43.8, 165-15, 43.8);
              $pdf->Ln(4.5);
              $pdf->SetFont('Arial','',8.5);
              $pdf->Cell(0, 6, 'Nomor : '.$nopkwt.'', 0, 0, 'C' );
              $pdf->Ln(10);
              $pdf->SetFont('Arial','',10);
              $pdf->Cell(0, 5, 'Yang bertanda tangan dibawah ini :', 0, 0, 'L' );
              $pdf->Ln(8);
              $pdf->Cell(7);
              $pdf->Cell(5, 5, 'I.', 0, 0, 'L' );
              $pdf->Cell(45, 5, 'Nama Lengkap', 0, 0, 'L' );
              $pdf->Cell(5, 5, ':', 0, 0, 'L' );
              $pdf->SetFont('Arial','B',10);
              $pdf->Cell(0, 5, 'LUTHFI IBRAHIM LUQMAN', 0, 0, 'L' );

              $pdf->SetFont('Arial','',10);
              $pdf->Ln(6);
              $pdf->Cell(12);
              $pdf->Cell(45, 5, 'NIK', 0, 0, 'L' );
              $pdf->Cell(5, 5, ':', 0, 0, 'L' );
              $pdf->SetFont('Arial','B',10);
              $pdf->Cell(0, 5, '3273042103770001', 0, 0, 'L' );

              $pdf->SetFont('Arial','',10);
              $pdf->Ln(6);
              $pdf->Cell(12);
              $pdf->Cell(45, 5, 'NRP', 0, 0, 'L' );
              $pdf->Cell(5, 5, ':', 0, 0, 'L' );
              $pdf->SetFont('Arial','B',10);
              $pdf->Cell(0, 5, '01065', 0, 0, 'L' );

              $pdf->SetFont('Arial','',10);
              $pdf->Ln(6);
              $pdf->Cell(12);
              $pdf->Cell(45, 5, 'Jabatan', 0, 0, 'L' );
              $pdf->Cell(5, 5, ':', 0, 0, 'L' );
              $pdf->SetFont('Arial','B',10);
              $pdf->Cell(0, 5, 'KEPALA BAGIAN HRD & GA', 0, 0, 'L' );

              $pdf->Ln(10);
              $pdf->SetFont('Arial','',10);
              $pdf->Cell(71, 5, 'Dalam hal ini bertindak untuk dan atas nama', 0, 0, 'L' );
              $pdf->SetFont('Arial','B',10);
              $pdf->Cell(51, 5, 'PT. RINDANG JATI SPINNING,', 0, 0, 'L' );
              $pdf->SetFont('Arial','',10);
              $pdf->Cell(20, 5, 'yang selanjutnya disebut sebagai', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->SetFont('Arial','B',10);
              $pdf->Cell(71, 5, 'Pihak Pertama', 0, 0, 'L' );
              $pdf->SetFont('Arial','',10);
              $pdf->Ln(8);
              $pdf->Cell(7);
              $pdf->Cell(5, 5, 'II.', 0, 0, 'L' );
              $pdf->Cell(45, 5, 'Nama Lengkap', 0, 0, 'L' );
              $pdf->Cell(5, 5, ':', 0, 0, 'L' );
              $pdf->SetFont('Arial','B',10);
              $pdf->Cell(0, 5, ''.$nama_karyawan.'', 0, 0, 'L' );

              $pdf->SetFont('Arial','',10);
              $pdf->Ln(6);
              $pdf->Cell(12);
              $pdf->Cell(45, 5, 'NIK', 0, 0, 'L' );
              $pdf->Cell(5, 5, ':', 0, 0, 'L' );
              $pdf->SetFont('Arial','B',10);
              $pdf->Cell(0, 5, ''.$nik.'', 0, 0, 'L' );

              $pdf->SetFont('Arial','',10);
              $pdf->Ln(6);
              $pdf->Cell(12);
              $pdf->Cell(45, 5, 'Tempat, Tanggal Lahir', 0, 0, 'L' );
              $pdf->Cell(5, 5, ':', 0, 0, 'L' );
              $pdf->SetFont('Arial','B',10);
              $pdf->Cell(0, 5, ''.$ttl.'', 0, 0, 'L' );

              $pdf->SetFont('Arial','',10);
              $pdf->Ln(6);
              $pdf->Cell(12);
              $pdf->Cell(45, 5, 'Alamat Tempat Tinggal', 0, 0, 'L' );
              $pdf->Cell(5, 5, ':', 0, 0, 'L' );
              $pdf->SetFont('Arial','',10);
              $pdf->Cell(30, 5, 'Dusun/Dukuh', 0, 0, 'L' );
              $pdf->Cell(5, 5, ':', 0, 0, 'L' );
              $pdf->SetFont('Arial','B',10);
              $pdf->Cell(0, 5, ''.$alamat.'', 0, 0, 'L' );
              $pdf->SetFont('Arial','',10);
              $pdf->Ln(6);
              $pdf->Cell(62);
              $pdf->Cell(30, 5, 'Kelurahan', 0, 0, 'L' );
              $pdf->Cell(5, 5, ':', 0, 0, 'L' );
              $pdf->SetFont('Arial','B',10);
              $pdf->Cell(0, 5, ''.$kel.'', 0, 0, 'L' );
              $pdf->SetFont('Arial','',10);
              $pdf->Ln(6);
              $pdf->Cell(62);
              $pdf->Cell(30, 5, 'Kecamatan', 0, 0, 'L' );
              $pdf->Cell(5, 5, ':', 0, 0, 'L' );
              $pdf->SetFont('Arial','B',10);
              $pdf->Cell(0, 5, ''.$kec.'', 0, 0, 'L' );
              $pdf->SetFont('Arial','',10);
              $pdf->Ln(6);
              $pdf->Cell(62);
              $pdf->Cell(30, 5, 'Kota/Kabupaten', 0, 0, 'L' );
              $pdf->Cell(5, 5, ':', 0, 0, 'L' );
              $pdf->SetFont('Arial','B',10);
              $pdf->Cell(0, 5, ''.$kota.'', 0, 0, 'L' );
              $pdf->SetFont('Arial','',10);

              $pdf->Ln(6);
              $pdf->Cell(12);
              $pdf->Cell(45, 5, 'No. Telp/HP', 0, 0, 'L' );
              $pdf->Cell(5, 5, ':', 0, 0, 'L' );
              $pdf->SetFont('Arial','B',10);
              $pdf->Cell(0, 5, ''.$nohp.'', 0, 0, 'L' );
              $pdf->SetFont('Arial','',10);

              $pdf->Ln(6);
              $pdf->Cell(12);
              $pdf->Cell(45, 5, 'E-mail', 0, 0, 'L' );
              $pdf->Cell(5, 5, ':', 0, 0, 'L' );
              $pdf->SetFont('Arial','B',10);
              $pdf->Cell(0, 5, ''.$email.'', 0, 0, 'L' );

              $pdf->Ln(10);
              $pdf->SetFont('Arial','',10);
              $pdf->Cell(133, 5, 'Dalam hal ini bertindak untuk dan atas nama pribadi, yang untuk selanjutnya disebut', 0, 0, 'L' );
              $pdf->SetFont('Arial','B',10);
              $pdf->Cell(30, 5, 'Pihak Kedua.', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(25, 5, 'Pihak Pertama', 0, 0, 'L' );
              $pdf->SetFont('Arial','',10);
              $pdf->Cell(7, 5, 'dan', 0, 0, 'L' );
              $pdf->SetFont('Arial','B',10);
              $pdf->Cell(22, 5, 'Pihak Kedua', 0, 0, 'L' );
              $pdf->SetFont('Arial','',10);
              $pdf->Cell(62, 5, 'secara bersama-sama disebut sebagai', 0, 0, 'L' );
              $pdf->SetFont('Arial','B',10);
              $pdf->Cell(35, 5, 'Kedua Belah Pihak.', 0, 0, 'L' );
              $pdf->SetFont('Arial','',10);
              $pdf->Ln(10);
              $pdf->Cell(18, 5, 'Dengan ini', 0, 0, 'L' );
              $pdf->SetFont('Arial','B',10);
              $pdf->Cell(33, 5, 'Kedua Belah Pihak', 0, 0, 'L' );
              $pdf->SetFont('Arial','',10);
              $pdf->Cell(0, 5, 'dalam keadaan sadar, tanpa paksaan dan dengan itikad baik telah sepakat dan setuju', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(0, 5, 'mengadakan perikatan dalam bentuk perjanjian kerja untuk waktu tertentu dengan ketentuan dan persyaratan sebagai', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(0, 5, 'berikut :', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '1.', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'Pihak Pertama akan memperkerjakan Pihak Kedua dengan ketentuan sebagai berikut :', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, 'a.', 0, 0, 'L' );
              $pdf->Cell(45, 5, 'Masa Kontrak', 0, 0, 'L' );
              $pdf->Cell(5, 5, ':', 0, 0, 'L' );
              $pdf->SetFont('Arial','B',10);
              $pdf->Cell(8, 5, ''.$masa_tahun.'', 0, 0, 'L' );
              $pdf->SetFont('Arial','',10);
              $pdf->Cell(14, 5, 'Tahun', 0, 0, 'L' );
              $pdf->SetFont('Arial','B',10);
              $pdf->Cell(8, 5, ''.$masa_bulan.'', 0, 0, 'L' );
              $pdf->SetFont('Arial','',10);
              $pdf->Cell(14, 5, 'Bulan', 0, 0, 'L' );
              $pdf->SetFont('Arial','B',10);
              $pdf->Cell(8, 5, '0', 0, 0, 'L' );
              $pdf->SetFont('Arial','',10);
              $pdf->Cell(14, 5, 'Hari', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, 'b.', 0, 0, 'L' );
              $pdf->Cell(45, 5, 'Waktu Kontrak', 0, 0, 'L' );
              $pdf->Cell(5, 5, ':', 0, 0, 'L' );
              $pdf->SetFont('Arial','B',10);
              $pdf->Cell(40, 5, ''.$_wawal.'', 0, 0, 'L' );
              $pdf->SetFont('Arial','',10);
              $pdf->Cell(14, 5, 's.d', 0, 0, 'L' );
              $pdf->SetFont('Arial','B',10);
              $pdf->Cell(20, 5, ''.$_wakhir.'', 0, 0, 'L' );
              $pdf->SetFont('Arial','',10);
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, 'c.', 0, 0, 'L' );
              $pdf->Cell(45, 5, 'Jabatan', 0, 0, 'L' );
              $pdf->Cell(5, 5, ':', 0, 0, 'L' );
              $pdf->SetFont('Arial','B',10);
              $pdf->Cell(0, 5, ''.$jabatan.' - '.$divisi.'', 0, 0, 'L' );
              $pdf->SetFont('Arial','',10);
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, 'd.', 0, 0, 'L' );
              $pdf->Cell(45, 5, 'Penempatan', 0, 0, 'L' );
              $pdf->Cell(5, 5, ':', 0, 0, 'L' );
              $pdf->SetFont('Arial','B',10);
              $pdf->Cell(0, 5, 'PT. Rindang Jati Dept. '.$departement.' - Kab. Pemalang', 0, 0, 'L' );
              $pdf->SetFont('Arial','',10);
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '2.', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'Perjanjian Kerja Waktu Tertentu ini didasarkan pada waktu kerja seperti tercantum pada poin 1 (Satu) Huruf B.', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '3.', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'Pihak Pertama dalam Perjanjian Kerja Waktu Tertentu ini memberikan upah dan tunjangan-tunjangan kepada Pihak', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'Kedua sebagai berikut :', 0, 0, 'L' );

              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, 'a.', 0, 0, 'L' );
              $pdf->Cell(45, 5, 'Upah Pokok', 0, 0, 'L' );
              $pdf->Cell(5, 5, ':', 0, 0, 'L' );
              $pdf->SetFont('Arial','B',10);
              $pdf->Cell(8, 5, 'Rp. '.number_format($upah).'      * Upah Pokok 50%    :  Rp. '.number_format($_upahsetengah).'', 0, 0, 'L' );
              $pdf->SetFont('Arial','',10);

              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, 'b.', 0, 0, 'L' );
              $pdf->Cell(45, 5, 'Tunjangan Jabatan', 0, 0, 'L' );
              $pdf->Cell(5, 5, ':', 0, 0, 'L' );
              $pdf->SetFont('Arial','B',10);
              $pdf->Cell(8, 5, 'Rp. '.number_format($tunjab).'', 0, 0, 'L' );
              $pdf->SetFont('Arial','',10);

              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, 'c.', 0, 0, 'L' );
              $pdf->Cell(45, 5, 'Premi Kehadiran', 0, 0, 'L' );
              $pdf->Cell(5, 5, ':', 0, 0, 'L' );
              $pdf->SetFont('Arial','B',10);
              $pdf->Cell(8, 5, 'Rp. '.number_format($premi).'', 0, 0, 'L' );
              $pdf->SetFont('Arial','',10);

              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'Tidak masuk kerja dengan alasan apapun termasuk Cuti Tahunan akan mengurangi nominal Premi Kehadiran Sebesar', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(0, 5, '50% per 1 Harinya.', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'Apabila Pihak Kedua mengundurkan diri dari pekerjaannya, namun tidak melaksanakan prosedur pengunduran diri', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(95, 5, 'sebagaimana yang berlaku di Perusahaan, yaitu melakukan', 0, 0, 'L' );
              $pdf->SetFont('Arial','B',10);
              $pdf->Cell(95, 5, 'Pemberitahuan Wajib dengan Surat Pengunduran Diri', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(95, 5, 'yang telah disetujui oleh Kepala Regu dan Kepala Bagiannya paling lambat 15 hari sebelumnya kepada Pihak', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(16, 5, 'Pertama,', 0, 0, 'L' );
              $pdf->SetFont('Arial','',10);
              $pdf->Cell(0, 5, 'maka Pihak Kedua hanya berhak menerima upah pokok sebesar 50%* dari yang tertera diatas dan', 0, 0, 'L' );
              $pdf->AddPage();
              $pdf->Ln(10);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'kehilangan hak atas tunjangan jabatan dan premi kehadirannya. Upah pokok akan dilakukan penyesuaian apabila', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'ada keputusan perubahan Upah Minimum Kabupaten/Kota (UMR) Pemalang dari pihak Disnaker Kab. Pemalang. ', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'Penyerahan upah akan dilakukan setiap tanggal 2 (Dua) setiap Bulannya.', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '4.', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'Hak dan Kewajiban Pihak Kedua :', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, 'a.', 0, 0, 'L' );
              $pdf->Cell(45, 5, 'Pihak kedua menyatakan setuju dan menerima ketentuan yang di keluarkan Pihak Pertama.', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, 'b.', 0, 0, 'L' );
              $pdf->Cell(45, 5, 'Pihak kedua bersedia menjalani masa kontrak kerja sebagaimana tercantum dalam pont 1 (Satu) di atas.', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, 'c.', 0, 0, 'L' );
              $pdf->Cell(45, 5, 'Pihak Kedua berkewajiban melaksanakan pekerjaan yang ditugaskan dengan baik, jujur, disiplin dan penuh', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(45, 5, 'rasa tanggung jawab.', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, 'd.', 0, 0, 'L' );
              $pdf->Cell(45, 5, 'Pihak Kedua berjanji tidak akan membocorkan rahasia perusahaan', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, 'e.', 0, 0, 'L' );
              $pdf->Cell(45, 5, 'Pihak Kedua sepakat tidak akan menuntut insentif atau imbalan lain dalam nama maupun bentuk apapun', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(45, 5, 'selain yang diberikan perusahaan sebagaimana tertuang pada lampiran perjanjian kerja ini, atas segala bentuk', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(45, 5, 'ciptaan, invensi atau karya apapun yang terkait dengan Hak Atas Kekayaan Intelektual (HAKI), yang dihasilkannya', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(45, 5, 'selama dalam hubungan kerja dengan perusahaan.', 0, 0, 'L' );

              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, 'f.', 0, 0, 'L' );
              $pdf->Cell(45, 5, 'Pada akhir masa kontrak, Pihak Kedua harus mengembalikan asset perusahaan (data hard copy & soft copy)', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(45, 5, 'dengan mengisi clearance sheet dan ditandatangani oleh PIC Departement terkait. Apabila tidak, maka akan', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(45, 5, 'diproses secara perdata/pidana.', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, 'g.', 0, 0, 'L' );
              $pdf->Cell(45, 5, 'Penghasilan pada periode akhir masa kontrak akan diberikan setelah point 4 (Empat) huruf (f) tersebut diatas', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(45, 5, 'dilaksanakan', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '5.', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'Pihak Kedua bersedia mematuhi semua Peraturan & Ketentuan serta Kebijakan yang di keluarkan Pihak Pertama', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'dan/atau ketenagakerjaan yang berlaku.', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '6.', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'Promosi, mutasi dan atau demosi merupakan hak dan wewenang Pihak Pertama sepenuhnya, dengan pemberitahuan', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'kepada Pihak Kedua sebelum pelaksanaanya.', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '7.', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'Pihak Kedua bersedia dengan ketentuan hari dan jam kerja yang ditentukan oleh Pihak Pertama yaitu :', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, 'a.', 0, 0, 'L' );
              $pdf->Cell(45, 5, 'Pekerja bekerja 6 (Enam) hari dalam seminggu dan 7 (Tujuh) jam/hari atau 40 (Empat Puluh) jam seminggu', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, 'b.', 0, 0, 'L' );
              $pdf->Cell(45, 5, 'Pihak Kedua akan bekerja pada salah satu jam kerja yang telah ditentukan oleh Pihak Pertama sebagai berikut :', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(8, 5, 'i.', 0, 0, 'L' );
              $pdf->Cell(50, 5, 'General Shift', 0, 0, 'L' );
              $pdf->Cell(5, 5, ':', 0, 0, 'L' );
              $pdf->Cell(5, 5, '08.00 s.d 16.00 WIB', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(8, 5, 'ii.', 0, 0, 'L' );
              $pdf->Cell(50, 5, 'Shift', 0, 0, 'L' );
              $pdf->Cell(5, 5, ':', 0, 0, 'L' );
              $pdf->Cell(25, 5, 'Shift Pagi', 0, 0, 'L' );
              $pdf->Cell(5, 5, ':', 0, 0, 'L' );
              $pdf->Cell(5, 5, '06.00 s.d 14.00 WIB', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(8, 5, '', 0, 0, 'L' );
              $pdf->Cell(50, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, ':', 0, 0, 'L' );
              $pdf->Cell(25, 5, 'Shift Siang', 0, 0, 'L' );
              $pdf->Cell(5, 5, ':', 0, 0, 'L' );
              $pdf->Cell(5, 5, '14.00 s.d 22.00 WIB', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(8, 5, '', 0, 0, 'L' );
              $pdf->Cell(50, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, ':', 0, 0, 'L' );
              $pdf->Cell(25, 5, 'Shift Malam', 0, 0, 'L' );
              $pdf->Cell(5, 5, ':', 0, 0, 'L' );
              $pdf->Cell(5, 5, '22.00 s.d 06.00 WIB', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, 'c.', 0, 0, 'L' );
              $pdf->Cell(45, 5, 'Jika Perusahaan (Pihak Pertama) memerlukan kerja lembur karena ada pekerjaan yang harus segera diselesaikan,', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(45, 5, 'maka pekerja (Pihak Kedua) diwajibkan melaksanakan dan menyelesaikan pekerjaan sesuai perintah atasan.', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(45, 5, 'langsung.', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '8.', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'Pelanggaran yang dilakukan oleh Pihak Kedua atas seluruh aturan dalam perjanjian ini dan/atau aturan lainya yang', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'dikeluarkan Pihak Pertama terkait hubungan kerja di Perusahaan, akan diberikan Surat Peringatan sesuai dengan ', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'bobot dan tingkat kesalahan. Bentuk Sanksi yang akan diberikan dengan pembinaan sesuai dengan tingkat dan bobot', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'kesalahan atau pelanggaran yang dilakukan, sebagai berikut :', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, 'a.', 0, 0, 'L' );
              $pdf->Cell(45, 5, 'Surat Peringatan Tingkat I (Pertama)', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, 'b.', 0, 0, 'L' );
              $pdf->Cell(45, 5, 'Surat Peringatan Tingkat II (Kedua)', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, 'c.', 0, 0, 'L' );
              $pdf->Cell(45, 5, 'Surat Peringatan Tingkat II (Ketiga)', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, 'd.', 0, 0, 'L' );
              $pdf->Cell(45, 5, 'Pemutusan Hubungan Kerja (PHK)', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '9.', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'Pihak Kedua dinyatakan mengundurkan diri dan atau dapat dilakukan Pemutusan Hubungan Kerja (PHK)  tanpa', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'syarat apabila :', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, 'a.', 0, 0, 'L' );
              $pdf->Cell(45, 5, 'Tidak masuk kerja 2 (Dua) hari berturut turut tanpa pemberitahuan dan atau surat keterangan.', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, 'b.', 0, 0, 'L' );
              $pdf->Cell(45, 5, 'Terdapat izin tidak masuk kerja selama 3 (Tiga) hari dalam 1 (satu) bulan dengan alasan apapun, kecuali ada', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(45, 5, 'kebijakan dari Pihak Pertama.', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'Dan Pihak Kedua membebaskan Pihak Pertama dari kewajiban untuk memberikan uang sisa kontrak kerja, ', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'pesangon dan dalam bentuk lainnya dalam kaitannya dengan Pemutusan Hubungan Kerja (PHK) tersebut. ', 0, 0, 'L' );
              $pdf->AddPage();
              $pdf->Ln(15);
              $pdf->Cell(5, 5, '10.', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'Apabila Pihak Kedua menerima sanksi sebagaimana poin 8 (Delapan), dan sudah mendapatkan pembinaan dari', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'Pihak Pertama, namun Pihak Kedua tetap tidak dapat memperbaiki perilaku dan/atau perfomance kerja maka', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'Pihak Pertama dapat melakukan Pemutusan Hubungan Kerja (PHK) tanpa harus menunggu berakhirnya masa ', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'perjanjian kerja dan Pihak Kedua membebaskan Pihak Pertama dari kewajiban untuk memberikan uang sisa kontrak, ', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'pesangon atau dalam bentuk lainnya.', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '11.', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'Pihak Pertama dapat memberikan denda kepada Pihak Kedua, apabila Pihak Kedua terbukti melakukan pelanggaran', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'yang mengakibatkan adanya kerugian materiil.', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '12.', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'Pengunduran diri oleh Pihak Kedua selama berlangsungnya perjanjian ini hanya dapat dilakukan dengan persetujuan', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'Pihak Pertama dengan Pemberitahuan Wajib sebagaimana tertera di poin 3 (Tiga).', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '13.', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'Tata Tertib Perusahaan yang harus di taati oleh Pihak Kedua meliputi :', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, 'a.', 0, 0, 'L' );
              $pdf->Cell(45, 5, 'Waktu Kerja dan Absensi', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(7, 5, 'i.', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'Pekerja wajib mengikuti Apel dan Do\'a bersama 15 dan atau 20 menit sebelum jam kerja dimulai.', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(7, 5, 'ii.', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'Terlambat datang harus membuat surat ijin terlambat, yang kebijaksanaan diijinkan dan atau tidak', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(7, 5, '', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'diijinkan masuk kerja diserahkan kepada atasan yang bersangkutan.', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(7, 5, 'iii.', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'Apabila Pihak Kedua yang terlambat tidak boleh masuk / dipulangkan, maka updah pada hari tersebut', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(7, 5, '', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'tidak dibayar.', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(7, 5, 'iv.', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'Meninggalkan tugas pada jam kerja untuk kepentingan pribadi harus minta ijin atasan langsung dengan', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(7, 5, '', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'ijin tertulis dan di ketahui oleh Personalia.', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(7, 5, 'v.', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'Pihak Kedua tanpa dilengkapi surat ijin tertulis sesuai dengan point (iv), tidak di perkenankan meninggalkan', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(7, 5, '', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'perusahaan.', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(7, 5, 'vi.', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'Pihak Kedua yang tidak masuk kerja harus segera menunjukan bukti ijin tertulis kepada atasan langsung,', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(7, 5, '', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'apabila tidak ada bukti tertulis yang sah maka di anggap mangkir dan upah tidak dibayarkan.', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, 'b.', 0, 0, 'L' );
              $pdf->Cell(45, 5, 'Absen', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(7, 5, 'i.', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'Setiap karyawan wajib melaksanakan absensi pada saat masuk dan pulang kerja.', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(7, 5, 'ii.', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'Karyawan yang tidak melaksanakan absensi pada saat masuk/pulang kerja maka di anggap tidak masuk kerja', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(7, 5, 'ii.', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'atau mangkir dan upah tidak dibayarkan.', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, 'c.', 0, 0, 'L' );
              $pdf->Cell(45, 5, 'Setiap karyawan wajib memakai tanda pengenal selama berada di lingkungan dan atau area perusahaan', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, 'd.', 0, 0, 'L' );
              $pdf->Cell(45, 5, 'Larangan bagi karyawan', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(7, 5, 'i.', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'Karyawan / ti dilarang tidur pada jam kerja (SP 3).', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(7, 5, 'ii.', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'Karyawan / ti dilarang merokok di seluruh area perusahaan.', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(7, 5, 'iii.', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'Karyawan / ti dilarang meninggalkan pekerjaannya tanpa perintah/tugas dari atasannya.', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(7, 5, 'iv.', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'Karyawan / ti dilarang bersorak-sorak, berteriak-teriak mengeluarkan suara yang keras, membuat', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(7, 5, '', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'kegaduhan dan bertingkah laku tidak baik sehingga mempengaruhi ketenangan kerja.', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(7, 5, 'v.', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'Karyawan / ti dilarang membawa makanan ke dalam ruangan produksi.', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(7, 5, 'vi.', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'Karyawan / ti dilarang berjualan makanan di dalam lingkungan perusahaan.', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(7, 5, 'vii.', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'Karyawan / ti dilarang makan pada jam kerja.', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '14.', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'Dalam hal perjanjian akan berakhir dan pada pihak bermaksud untuk melanjutkan atau tidak melanjutkan perjanjian', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'ini maka Para Pihak berkewajiban menyampaikan informasi tersebut selambat-lambatnya 2 (Dua) minggu sebelum', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'perjanjian ini berakhir.', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '15.', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'Bilamana hubungan kerja antara Pihak Pertama dan Pihak Kedua telah berakhir dan telah diberitahukan bahwa', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'Pihak Kedua masih mempunyai sisa upah sesuai dengan masa kerja yang telah dijalaninya, namun Pihak Kedua', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'tidak melakukan pengambilan lebih dari 6 (Enam) Bulan dan atau 180 Hari sejak tanggal pengupahan terakhir,', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'maka upah tersisa tersebut akan di alihkan dan digunakan oleh Pihak Pertama dalam program bantuan sosial', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'Perusahaan dan Pihak Kedua tidak mempunyai hak lagi untuk menuntut upah tersisa tersebut dan atau ganti', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'rugi lainnya kepada Pihak Pertama.', 0, 0, 'L' );
              $pdf->AddPage();
              $pdf->Ln(15);
              $pdf->Cell(5, 5, '16', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'Jika salah satu pihak melanggar dan tidak mematuhi isi Surat Perjanjian Kerja Waktu Tertentu ini, serta', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'musyawarah sebagaimana telah ditempuh juga tidak mencapai kesepakatan maka masing-masing pihak berhak', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(5, 5, '', 0, 0, 'L' );
              $pdf->Cell(0, 5, 'untuk meminta penyelesaian hukum kepada pihak yang berwenang yakni di kantor Dinas Tenaga Kerja setempat.', 0, 0, 'L' );
              $pdf->Ln(10);
              $pdf->Cell(0, 5, 'Perjanjian Kerja ini mulai berlaku sejak sebagaimana tertulis dalam point 1 (Satu) huruf (b), dibuat dalam keadaan ', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(0, 5, 'sadar, sehat jasmani dan rohani serta tanpa adanya tekanan dari pihak manapun dan siapapun, di atas kertas', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(0, 5, 'bermaterai secukupnya yang mempunyai kekuatan hukum.', 0, 0, 'L' );
              $pdf->Ln(15);
              $pdf->Cell(130, 5, '', 0, 0, 'L' );
              $pdf->Cell(60, 5, 'Pemalang, '.$_wawal.'', 0, 0, 'R' );
              $pdf->Ln(15);
              $pdf->Cell(20, 5, '', 0, 0, 'L' );
              $pdf->Cell(120, 5, 'PIHAK PERTAMA,', 0, 0, 'L' );
              $pdf->Cell(30, 5, 'PIHAK KEDUA,', 0, 0, 'L' );
              if($ttd!="no"){
                  $urlimagess = "".base_url()."uploads/".$ttd."";
                  $pdf->Image($urlimagess, 135, 95, 55, 0, 'png');
              }
              $urlimagess1 = "".base_url()."assets/ttd_hrd.png";
              $pdf->Image($urlimagess1, 15, 95, 55, 0, 'png');
              $pdf->Ln(40);
              $pdf->Cell(15, 5, '', 0, 0, 'L' );
              $pdf->Cell(105, 5, 'LUTHFI IBRAHIM LUQMAN', 0, 0, 'L' );
              $pdf->Line(20, 130, 90-15, 130);
              $pdf->Line(20, 130.5, 90-15, 130.5);
              $pdf->Cell(70, 5, ''.$nama_karyawan.'', 0, 0, 'C' );
              $pdf->Ln(6);
              $pdf->Cell(15, 5, '', 0, 0, 'L' );
              $pdf->Cell(105, 5, 'Kepala Bagian HRD & GA', 0, 0, 'L' );
              $pdf->Ln(5);
              $pdf->Cell(15, 5, '', 0, 0, 'L' );
              $pdf->Cell(105, 5, 'PT. Rindang Jati Spinning', 0, 0, 'L' );

              $pdf->Output('I','Cetak-PKTW-'.$nama_karyawan.'.pdf'); 
    } else {
      echo "Token Error...";
    } 
  } //end
  
  
}
?>